# R for travis: https://docs.travis-ci.com/user/languages/r
language: r
cache: packages
warnings_are_errors: false

r:
  - release

# do not build vignettes
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual

# for codecov
r_packages:
  - covr
  - Rscript -e 'library(covr); options(covr.flags = c(CXXFLAGS = "-O2", LDFLAGS=""))'

# only report coverage after build is successful
after_success:
  - Rscript -e 'library(covr); options(covr.flags = c(CXXFLAGS = "-O2", LDFLAGS="")); codecov()' # covr::codecov


notifications:
  email:
    on_success: change
    on_failure: change


